---
title: "TF Classification"
author: "Arend Vancraeynest"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE, 
                      message=FALSE,
                      tidy.opts=list(width.cutoff=60)
                      )
```

```{r here}
library(here)
```

## Overview

Here, you must describe the goal of the analyses documented in this documented.

## Proteome metadata
### Ready the data for R manipulation
```{r}
library(Biostrings)
proteomes <- list.files(here("data", "Proteomes"), full.names = TRUE)

seqs <- lapply(proteomes, readAAStringSet)

# A file containing the genome assembly versions and reference papers has been made manually 
extra_data <- read.table(here("data", "Genome_references.txt"), header = FALSE, sep = "\t")
```


### Generate a summary dataframe
```{r}
# Initiate the dataframe based on the species names contained within the file names 
# (genus abbreviated in 1 letter, species epithet in full, divided by a '.')
species_names <- gsub(".*/([a-z]\\.[a-z]+)_((cv|ssp)\\.[a-z0-9-]+)?.*", "\\1 \\2", proteomes, ignore.case = TRUE)
species_names <- gsub(" $", "", species_names)
df <- data.frame(Species_name = species_names)


# Add the Genome Assembly version
df$Genome_assembly_version <- extra_data$V1

# Count the number of proteins and genes for each species and append to an initiated dataframe
check_isoforms <- function(seqlist = NULL) {
  combined_list <- lapply(seq_along(seqlist), function(x){
    all_seqs <- names(seqlist[[x]])
    proteins <- length(all_seqs)
    
    # Substring the unique gene names from the different types of annotation
    unique_seqs <- gsub("^.*gene=", "", all_seqs, ignore.case = TRUE)
    unique_seqs <- gsub("\\s.*$", "", unique_seqs)
    unique_seqs <- gsub("\\.t?[0-9]+(.p)?$", "", unique_seqs)
    
    # Only retain unique gene handles
    unique_seqs <- unique(unique_seqs)
    genes <- length(unique_seqs)

    return(c(proteins, genes))
  }
  )
  df$Coding_genes <<- sapply(combined_list, "[[", 2)
  df$Annotated_proteins <<- sapply(combined_list, "[[", 1)
}

check_isoforms(seqs)

# Add the reference papers
df$References <- extra_data$V2

# Tidy up the dataframe to make it more reader-friendly by replacing underscores by spaces in the headers
names(df) <- gsub("_", " ", names(df))
```


### Clean up the protein FASTA files
```{r}
library(tidyverse)

primary_transcripts <- function(seq_stringset = NULL){
  n <- names(seq_stringset)
  
  # For each transcript, find the encoding gene
  unique_seqs <- gsub("^.*gene=", "", n, ignore.case = TRUE)
  unique_seqs <- gsub("\\s.*$", "", unique_seqs)
  unique_seqs <- gsub("\\.t?[0-9]+(.p)?$", "", unique_seqs)
  
  # Make a dataframe with the transcript names, gene names and sequence lengths
  # group by the gene names and only keep the longest sequence (which should by the primary)
  df_clean <- data.frame(names = n, clean_names = unique_seqs, len = width(seq_stringset)) %>% 
    group_by(clean_names) %>% 
    filter(len == max(len))
  
  # In some cases transcripts are duplicated (different id, but same length & sequence) --> keep only the first
  df_clean <- df_clean[!duplicated(df_clean$clean_names), ]
  
  # Return the AAStringset datatype filtered by the remaining names
  return(seq_stringset[df_clean$names])
}


# Create a new directory for the cleaned files
clean_directory <- here("products", "result_files", "Proteomes_clean")
if(dir.exists(clean_directory)){
  cat("Directory already exists!")
} else {
  dir.create(clean_directory)
}



# If the count of genes and proteins is not equal (aka more transcripts per gene instead of just the primary):
# apply the primary_transcript function. If equal: just copy the object
invisible(lapply(seq_along(seqs), function(x){
  if(df[x,]$'Coding genes' != df[x,]$'Annotated proteins'){
    stringset <- primary_transcripts(seqs[[x]])
  } else {stringset <- seqs[[x]]
  } 
  # Generate new file names for the clean data
  new_file_name <- gsub(" ", "_", paste(species_names[x], "PrimaryTranscript.pep"))
  
  # Write the stringset data to a fasta file
  if(!file.exists(here(clean_directory, new_file_name))){
    writeXStringSet(stringset, here(clean_directory, new_file_name), format = "fasta")
  }
  
  # As a nice side note, displays which file is being compiled
  return(message("File", x, "generated!\n"))
})
)

```


## Session info

This document was created under the following conditions:

```{r sessioninfo}
sessionInfo()
```