---
title: "Document name"
author: "Your Name"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                      warning=FALSE, 
                      message=FALSE,
                      tidy.opts=list(width.cutoff=60),
                      tidy=TRUE)
```

```{r here}
library(here)
```

## Overview

Here, you must describe the goal of the analyses documented in this documented.

## Analysis 1

### Making a heatmap
```{r fig.width=8, fig.height= 8}
library(pheatmap)
library(DESeq2)

tf_file <- "https://raw.githubusercontent.com/almeidasilvaf/brassicaceae_tfs/main/products/tables/tf_families_per_species.tsv"
tf_table <- read.table(tf_file, header = T)

# load data and subset
data <- read.delim(tf_file, header=T)
rownames(data) <- data$Family
data$Family <- NULL
data_matrix <- as.matrix(data)

# create heatmap using pheatmap
pheatmap(data_matrix, scale = "row")
```

### Phylogenetic species tree
```{r, fig.width=8, fig.height=8}
library(ggtree)

# A newick file with our relevant species was downloaded from TimeTree,
# andupdated with the cultivars/subspecies, as well as refined based on the scientific literature
tree_file <- here("data", "Better_species_tree.nwk.txt")
tree <- treeio::read.newick(tree_file)

# The display of the endpoint labels (aka species names) is improved:
# removed underscores, font converted into italics through a reach around
tree$tip.label <- gsub("_", " ", tree$tip.label)

# Reach around: names enclosed by paste(italic()) as character strings and later within ggtree function parsed
tree$tip.label <- gsub("(.+)", "paste(italic('\\1'))", tree$tip.label)

species_tree <- ggtree(tree) +
  xlim(NA, 40) +
  geom_tiplab(align=T, parse=T)
```


## Session info

This document was created under the following conditions:

```{r sessioninfo}
sessionInfo()
```